# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs: 
  build:
    docker: 
      - image: slacgismo/gridlabd:develop
    steps: 
      - checkout 
      - run: 
          name: Run version check
          command: |
            gridlabd --version=all
      - run:
          name: Run the Virtual Islanding Simulation
          command: |
            cd virtual_islanding
            mkdir output
            python3 run_gridlabd_main.py
          name: Run the IEEE 8500 Simulation
          command: |
            cd ../IEEE8500
            mkdir -p final_output
            more config/local.glm
            gridlabd ieee8500.glm
      - store_artifacts: 
            path: /root/project/output
