# create_loads.py

import sys
import json

with open(sys.argv[1],"r") as fh:
    model = json.load(fh)

count = 0
with open(sys.argv[2],"w") as fh:
    fh.write("// generated by create_loads.py\n")
    for load in [x for x,y in model["objects"].items() if y["class"] == "load"]:
        fh.write(f'#include using(LOAD={load}) "randomizer.glm"\n')
        count += 1

assert count > 0, f"no load objects found"
